Repository Azure/azure-orbital-integration, pull requests merged in 2022-09, with the labels that each got.

#120 Remove literal value from recent activity query.
  tcp-to-blob/README.md
Labels: documentation

#122 Update processor README
  examples/aqua-processor/README.md
Labels: documentation

#123 added a new line to the end of the files per task instructions
  central-logging/README.md
  central-logging/deploy/ADX/Functions/RT-STPS/GetRTSTPSProcessingStats.kql
  central-logging/deploy/ADX/Tables/AppExceptions.kql
  examples/aqua-processor/README.md
  examples/aqua-processor/deploy/deploy.sh
  examples/aqua-processor/run_rtstps.sh
  orbital-helper/tsconfig.json
  package.json
  tcp-to-blob/README.md
  tcp-to-blob/deploy/Dockerfile
  tcp-to-blob/deploy/Dockerfile-canary
  tcp-to-blob/deploy/ado-pipeline/prereq/prereq-azure-cli.sh
  tcp-to-blob/deploy/ado-pipeline/prereq/prereq-azure-pipeline.yml
  tcp-to-blob/deploy/az-cli/deploy.sh
  tcp-to-blob/deploy/bicep/deploy-core.sh
  tcp-to-blob/deploy/bicep/deploy.sh
  tcp-to-blob/deploy/check-required-env.sh
  tcp-to-blob/deploy/dashboard-template.json
  tcp-to-blob/deploy/env-defaults.sh
  tcp-to-blob/deploy/env-prereq-defaults.sh
  tcp-to-blob/deploy/tcp-to-blob-canary-template.yaml
  tcp-to-blob/deploy/tcp-to-blob-template.yaml
  tcp-to-blob/tsconfig.json
Labels: documentation, enhancement

#128 Improve Orbital Helper package declarations
  orbital-helper/package.json
  orbital-helper/src/index.ts
  tcp-to-blob/package.json
  tcp-to-blob/src/makeContactProfile.ts
  yarn.lock
Labels: enhancement

#115 Adding FileEventService source and README
  .gitignore
  file-event-service/README.md
  file-event-service/src/.vscode/launch.json
  file-event-service/src/.vscode/settings.json
  file-event-service/src/.vscode/tasks.json
  file-event-service/src/Actions/BlobDownloadEventAction.cs
  file-event-service/src/Actions/BlobUploadEventAction.cs
  file-event-service/src/Actions/DispatcherEventActionType.cs
  file-event-service/src/Actions/EventActionException.cs
  file-event-service/src/Actions/EventActionFactory.cs
  file-event-service/src/Actions/EventGridEventAction.cs
  file-event-service/src/Actions/IEventAction.cs
  file-event-service/src/Actions/ListenerEventActionType.cs
  file-event-service/src/Actions/Options/BlobDownloadActionOptions.cs
  file-event-service/src/Actions/Options/BlobUploadActionOptions.cs
  file-event-service/src/Actions/Options/EventGridEventActionOptions.cs
  file-event-service/src/Actions/Options/ScriptEventActionOptions.cs
  file-event-service/src/Actions/ScriptEventAction.cs
  file-event-service/src/Constants.cs
  file-event-service/src/Dispatchers/BaseEventDispatcher.cs
  file-event-service/src/Dispatchers/DispatcherException.cs
  file-event-service/src/Dispatchers/EventDispatcherFactory.cs
  file-event-service/src/Dispatchers/EventDispatcherType.cs
  file-event-service/src/Dispatchers/IEventDispatcher.cs
  file-event-service/src/Dispatchers/LocalFileSystemEventDispatcher.cs
  file-event-service/src/Dispatchers/LocalFileSystemEventProcessor.cs
  file-event-service/src/Dispatchers/Options/LocalFileSystemDispatcherOptions.cs
  file-event-service/src/Dispatchers/RenamedFileMetadata.cs
  file-event-service/src/FileEventService.csproj
  file-event-service/src/FileEventServiceTelemetryInitializer.cs
  file-event-service/src/Listeners/BaseEventListener.cs
  file-event-service/src/Listeners/EventListenerFactory.cs
  file-event-service/src/Listeners/EventListenerType.cs
  file-event-service/src/Listeners/IEventListener.cs
  file-event-service/src/Listeners/ListenerException.cs
  file-event-service/src/Listeners/Options/ServiceBusListenerOptions.cs
  file-event-service/src/Listeners/ServiceBusEventListener.cs
  file-event-service/src/Logging/LogMessage.cs
  file-event-service/src/Models/EventGridMessage.cs
  file-event-service/src/Models/FileMetadata.cs
  file-event-service/src/Options/FileEventServiceOptions.cs
  file-event-service/src/Program.cs
  file-event-service/src/Utilities/ConfigUtils.cs
  file-event-service/src/Utilities/EnumUtilitiesException.cs
  file-event-service/src/Utilities/EnumUtils.cs
  file-event-service/src/Utilities/JsonUtils.cs
  file-event-service/src/Workers/EventDispatcherWorker.cs
  file-event-service/src/Workers/EventListenerWorker.cs
  file-event-service/src/Workers/HeartbeatWorker.cs
  file-event-service/src/appsettings.template.json
  file-event-service/src/file-event-service.sample.json
Labels: documentation, enhancement

#133 Fixing github action to build file-event-service
  .github/workflows/dotnet-build.yml
Labels: bug

#131 Integrating FileEventService with aqua-processor
  blob-download-service/README.md
  blob-download-service/src/.vscode/launch.json
  blob-download-service/src/.vscode/tasks.json
  blob-download-service/src/BlobDownloadService.csproj
  blob-download-service/src/BlobDownloadServiceTelemetryInitializer.cs
  blob-download-service/src/Logging/LogMessage.cs
  blob-download-service/src/Models/BlobMetadata.cs
  blob-download-service/src/Models/EventGridMessage.cs
  blob-download-service/src/Options/BlobDownloadOptions.cs
  blob-download-service/src/Options/HeartbeatOptions.cs
  blob-download-service/src/Program.cs
  blob-download-service/src/Receivers/EventGridMessageArgs.cs
  blob-download-service/src/Receivers/EventHubReceiver.cs
  blob-download-service/src/Receivers/IEventGridMessageReceiver.cs
  blob-download-service/src/Receivers/Options/EventHubReceiverOptions.cs
  blob-download-service/src/Receivers/Options/ReceiverBaseOptions.cs
  blob-download-service/src/Receivers/Options/ServiceBusReceiverOptions.cs
  blob-download-service/src/Receivers/ReceiverBase.cs
  blob-download-service/src/Receivers/ReceiverException.cs
  blob-download-service/src/Receivers/ReceiverFactory.cs
  blob-download-service/src/Receivers/ReceiverType.cs
  blob-download-service/src/Receivers/ServiceBusReceiver.cs
  blob-download-service/src/Workers/BlobDownloadWorker.cs
  blob-download-service/src/Workers/HeartbeatWorker.cs
  blob-download-service/src/appsettings.sample.json
  examples/aqua-processor/README.md
  examples/aqua-processor/deploy/blob-download-service/appsettings.template.json
  examples/aqua-processor/deploy/blob-download-service/install-blob-download-service.sh
  examples/aqua-processor/deploy/deploy.sh
  examples/aqua-processor/deploy/env-template.sh
  examples/aqua-processor/deploy/file-event-service/FileEventService.service
  examples/aqua-processor/deploy/file-event-service/appsettings.template.json
  examples/aqua-processor/deploy/file-event-service/file-event-service.template.json
  examples/aqua-processor/deploy/file-event-service/install-file-event-service.sh
  examples/aqua-processor/deploy/file-event-service/prepare-artifacts.sh
  examples/aqua-processor/deploy/file-event-service/run-nasa-tools.sh
  examples/aqua-processor/deploy/inotify-rtstps/INotifyRTSTPS.service
  examples/aqua-processor/deploy/inotify-rtstps/inotify-rtstps.sh
  examples/aqua-processor/deploy/inotify-rtstps/install-inotify-rtstps.sh
  examples/aqua-processor/deploy/inotify-rtstps/prepare-artifacts.sh
  examples/aqua-processor/deploy/modules/aqua-processor-vm.bicep
  examples/aqua-processor/ipopp_log.sh
  examples/aqua-processor/run_rtstps.sh
  file-event-service/src/Workers/HeartbeatWorker.cs
  tcp-to-blob/deploy/bicep/storage.bicep
  tcp-to-blob/deploy/check-required-env.sh
  tcp-to-blob/deploy/env-defaults.sh
Labels: enhancement

#151 TCP-to-blob README changes
  tcp-to-blob/README.md
Labels: documentation

#134 Feature/heartbeat
  tcp-to-blob/README.md
  tcp-to-blob/deploy/bicep/storage.bicep
  tcp-to-blob/deploy/tcp-to-blob-canary-cron-template.yaml
  tcp-to-blob/package.json
  tcp-to-blob/src/makeEnvFiles.ts
  tcp-to-blob/src/tcp-to-blob.ts
Labels: enhancement
